/**
 * Realistic Varanasi Hub Seed Data with direct Agent Name and Login Account ID
 */

export function generateInitialDailyEntries() {
  const today = new Date();
  const year = today.getFullYear();
  const month = today.getMonth() + 1;
  const pad = (n) => String(n).padStart(2, '0');

  const entries = [
    // Today's entries (Balanced and Shortage mix)
    {
      id: 'de-today-1',
      agent_name: 'Rahul Sharma',
      login_account_id: 'LOG-VNS-101',
      entry_date: `${year}-${pad(month)}-${pad(today.getDate())}`,
      hub_location: 'Varanasi Hub',
      total_delivered: 48,
      cod_orders: 26,
      online_received: 14250,
      reported_cod_cash: 23500,
      note_500: 40,
      note_200: 15,
      note_100: 5,
      note_50: 0,
      note_20: 0,
      note_10: 0,
      coin_1: 0,
      actual_cash_tally: 23500,
      total_settled: 37750,
      cash_variance: 0,
      audit_status: 'Balanced',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'de-today-2',
      agent_name: 'Amit Patel',
      login_account_id: 'LOG-VNS-102',
      entry_date: `${year}-${pad(month)}-${pad(today.getDate())}`,
      hub_location: 'Varanasi Hub',
      total_delivered: 52,
      cod_orders: 31,
      online_received: 18600,
      reported_cod_cash: 28400,
      note_500: 50,
      note_200: 14,
      note_100: 5,
      note_50: 2,
      note_20: 0,
      note_10: 0,
      coin_1: 0,
      actual_cash_tally: 28400,
      total_settled: 47000,
      cash_variance: 0,
      audit_status: 'Balanced',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'de-today-3',
      agent_name: 'Vikram Singh',
      login_account_id: 'LOG-VNS-103',
      entry_date: `${year}-${pad(month)}-${pad(today.getDate())}`,
      hub_location: 'Varanasi Hub',
      total_delivered: 42,
      cod_orders: 22,
      online_received: 11200,
      reported_cod_cash: 19800,
      note_500: 35,
      note_200: 10,
      note_100: 2,
      note_50: 0,
      note_20: 0,
      note_10: 0,
      coin_1: 0,
      actual_cash_tally: 19700,
      total_settled: 30900,
      cash_variance: -100,
      audit_status: 'Shortage',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // Yesterday's entries
    {
      id: 'de-yest-1',
      agent_name: 'Rahul Sharma',
      login_account_id: 'LOG-VNS-101',
      entry_date: `${year}-${pad(month)}-${pad(Math.max(1, today.getDate() - 1))}`,
      hub_location: 'Varanasi Hub',
      total_delivered: 55,
      cod_orders: 30,
      online_received: 16500,
      reported_cod_cash: 27000,
      note_500: 48,
      note_200: 12,
      note_100: 6,
      note_50: 0,
      note_20: 0,
      note_10: 0,
      coin_1: 0,
      actual_cash_tally: 27000,
      total_settled: 43500,
      cash_variance: 0,
      audit_status: 'Balanced',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'de-yest-2',
      agent_name: 'Priya Verma',
      login_account_id: 'LOG-VNS-104',
      entry_date: `${year}-${pad(month)}-${pad(Math.max(1, today.getDate() - 1))}`,
      hub_location: 'Varanasi Hub',
      total_delivered: 39,
      cod_orders: 20,
      online_received: 9800,
      reported_cod_cash: 16400,
      note_500: 30,
      note_200: 7,
      note_100: 0,
      note_50: 0,
      note_20: 0,
      note_10: 0,
      coin_1: 0,
      actual_cash_tally: 16400,
      total_settled: 26200,
      cash_variance: 0,
      audit_status: 'Balanced',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },

    // 2 days ago (Surplus day)
    {
      id: 'de-2d-1',
      agent_name: 'Deepak Yadav',
      login_account_id: 'LOG-VNS-105',
      entry_date: `${year}-${pad(month)}-${pad(Math.max(1, today.getDate() - 2))}`,
      hub_location: 'Varanasi Hub',
      total_delivered: 44,
      cod_orders: 24,
      online_received: 12400,
      reported_cod_cash: 21500,
      note_500: 40,
      note_200: 8,
      note_100: 2,
      note_50: 0,
      note_20: 0,
      note_10: 0,
      coin_1: 0,
      actual_cash_tally: 21800,
      total_settled: 34200,
      cash_variance: 300,
      audit_status: 'Surplus',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'de-2d-2',
      agent_name: 'Sandeep Gupta',
      login_account_id: 'LOG-VNS-106',
      entry_date: `${year}-${pad(month)}-${pad(Math.max(1, today.getDate() - 2))}`,
      hub_location: 'Varanasi Hub',
      total_delivered: 47,
      cod_orders: 25,
      online_received: 13800,
      reported_cod_cash: 22600,
      note_500: 40,
      note_200: 13,
      note_100: 0,
      note_50: 0,
      note_20: 0,
      note_10: 0,
      coin_1: 0,
      actual_cash_tally: 22600,
      total_settled: 36400,
      cash_variance: 0,
      audit_status: 'Balanced',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
  ];

  return entries;
}

export function generateInitialRemittanceEntries() {
  const today = new Date();
  const year = today.getFullYear();
  const month = today.getMonth() + 1;
  const pad = (n) => String(n).padStart(2, '0');

  return [
    {
      id: 'rem-today',
      entry_date: `${year}-${pad(month)}-${pad(today.getDate())}`,
      hub_location: 'Varanasi Hub',
      deposit_bank: 'State Bank of India',
      deposit_branch: 'Varanasi Main Branch (Cantt)',
      cash_challan_no: 'SBI-VNS-2026-0915',
      cash_deposited: 65000,
      bank_utr_ref_no: 'SBIN00291823901',
      online_remitted: 44050,
      area_manager_name: 'Rajesh Kumar (AM)',
      manager_approval_status: 'Approved & Reconciled',
      signoff_date: `${year}-${pad(month)}-${pad(today.getDate())}`,
      remittance_audit_status: 'Verified • Bank Confirmed',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'rem-yest',
      entry_date: `${year}-${pad(month)}-${pad(Math.max(1, today.getDate() - 1))}`,
      hub_location: 'Varanasi Hub',
      deposit_bank: 'HDFC Bank',
      deposit_branch: 'Sigra Branch, Varanasi',
      cash_challan_no: 'HDFC-VNS-449102',
      cash_deposited: 43400,
      bank_utr_ref_no: 'HDFCR520260914008',
      online_remitted: 26300,
      area_manager_name: 'Rajesh Kumar (AM)',
      manager_approval_status: 'Approved & Reconciled',
      signoff_date: `${year}-${pad(month)}-${pad(Math.max(1, today.getDate() - 1))}`,
      remittance_audit_status: 'Verified • Bank Confirmed',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    }
  ];
}
